# Generated by Django 4.0.4 on 2023-12-26 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='api_key',
        ),
    ]
