# Generated by Django 2.2.7 on 2022-01-17 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestRecords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default='', max_length=250)),
                ('test_description', models.CharField(default='', max_length=250)),
                ('test_name', models.CharField(default='', max_length=250)),
                ('webcam_file', models.FileField(blank=True, upload_to='')),
                ('screen_file', models.FileField(blank=True, upload_to='')),
                ('key_log_file', models.FileField(blank=True, upload_to='')),
                ('merged_webcam_screen_file', models.FileField(blank=True, upload_to='')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'test_records_table',
            },
        ),
    ]
