# Generated by Django 2.2.7 on 2022-02-03 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChunksTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webcam_file', models.FileField(blank=True, upload_to='')),
            ],
            options={
                'db_table': 'chunk_records_table',
            },
        ),
    ]
