# Generated by Django 4.0.4 on 2022-07-27 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vpstestrecord',
            name='event_id',
            field=models.CharField(default='', max_length=1024),
        ),
    ]
