# Generated by Django 2.2.7 on 2022-02-09 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_app', '0002_chunkstest'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChunksTest2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webcam_file', models.FileField(blank=True, upload_to='')),
            ],
            options={
                'db_table': 'chunk_records_table2',
            },
        ),
        migrations.AlterField(
            model_name='testrecords',
            name='merged_webcam_screen_file',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='testrecords',
            name='screen_file',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='testrecords',
            name='webcam_file',
            field=models.CharField(default='', max_length=250),
        ),
    ]
