# Generated by Django 2.2.7 on 2022-02-10 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_app', '0003_auto_20220209_1412'),
    ]

    operations = [
        migrations.CreateModel(
            name='MegaTestRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default='', max_length=1024)),
                ('test_description', models.CharField(default='', max_length=1024)),
                ('test_name', models.CharField(default='', max_length=1024)),
                ('webcam_file', models.CharField(default='', max_length=1024)),
                ('screen_file', models.CharField(default='', max_length=1024)),
                ('merged_webcam_screen_file', models.CharField(default='', max_length=1024)),
                ('key_log_file', models.CharField(default='', max_length=1024)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'mega_test_records',
            },
        ),
    ]
