# Generated by Django 4.0.4 on 2022-08-25 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_app', '0003_vpstestrecord_user_playlist_selection'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vpstestrecord',
            old_name='user_playlist_selection',
            new_name='Account_info',
        ),
    ]
