# Generated by Django 2.2.7 on 2022-04-05 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_app', '0004_megatestrecord'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChunksTest',
        ),
        migrations.DeleteModel(
            name='ChunksTest2',
        ),
        migrations.AddField(
            model_name='megatestrecord',
            name='beanote_file',
            field=models.CharField(default='', max_length=1024),
        ),
    ]
