# Generated by Django 4.0.4 on 2022-09-27 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_app', '0004_rename_user_playlist_selection_vpstestrecord_account_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='vpstestrecord',
            name='app_type',
            field=models.TextField(default=''),
        ),
    ]
