# Generated by Django 2.2.7 on 2022-05-17 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_app', '0005_auto_20220405_1303'),
    ]

    operations = [
        migrations.CreateModel(
            name='VpsTestRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default='', max_length=1024)),
                ('test_description', models.CharField(default='', max_length=1024)),
                ('test_name', models.CharField(default='', max_length=1024)),
                ('user_files_timestamp', models.CharField(default='', max_length=1024)),
                ('webcam_file', models.CharField(default='', max_length=1024)),
                ('screen_file', models.CharField(default='', max_length=1024)),
                ('merged_webcam_screen_file', models.CharField(default='', max_length=1024)),
                ('key_log_file', models.CharField(default='', max_length=1024)),
                ('beanote_file', models.CharField(default='', max_length=1024)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'vps_test_records',
            },
        ),
    ]
