# Generated by Django 4.0.4 on 2022-10-03 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_app', '0005_vpstestrecord_app_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='vpstestrecord',
            name='youtube_file_copy',
            field=models.CharField(default='', max_length=1024),
        ),
    ]
