# Generated by Django 4.0.4 on 2022-05-20 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_app', '0006_vpstestrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='VpsIncomingTestRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default='', max_length=1024)),
                ('test_description', models.CharField(default='', max_length=1024)),
                ('test_name', models.CharField(default='', max_length=1024)),
                ('user_files_timestamp', models.CharField(default='', max_length=1024)),
                ('webcam_file', models.CharField(default='', max_length=1024)),
                ('screen_file', models.CharField(default='', max_length=1024)),
                ('merged_webcam_screen_file', models.CharField(default='', max_length=1024)),
                ('key_log_file', models.FileField(blank=True, upload_to='')),
                ('beanote_file', models.FileField(blank=True, upload_to='')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'managed': False,
            },
        ),
    ]
