# Generated by Django 4.0.4 on 2022-10-05 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_app', '0006_vpstestrecord_youtube_file_copy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vpstestrecord',
            name='app_type',
        ),
        migrations.RemoveField(
            model_name='vpstestrecord',
            name='youtube_file_copy',
        ),
    ]
