# Generated by Django 4.0.4 on 2022-10-05 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_app', '0007_remove_vpstestrecord_app_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vpstestrecord',
            name='app_type',
            field=models.TextField(default=''),
        ),
    ]
