# Generated by Django 4.0.4 on 2022-08-20 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserYoutubePlaylists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=1024)),
                ('playlist_id', models.CharField(max_length=1024)),
                ('playlist_title', models.CharField(max_length=1024)),
                ('playlist_enabled', models.BooleanField()),
            ],
            options={
                'db_table': 'user_youtube_playlists',
            },
        ),
    ]
