# Generated by Django 4.0.4 on 2023-03-06 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='youtubeuser',
            options={},
        ),
    ]
