# Generated by Django 4.0.4 on 2022-10-10 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0002_playlistsrecords'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PlaylistsRecords',
            new_name='PlaylistsRecord',
        ),
    ]
