# Generated by Django 4.0.4 on 2023-12-26 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0002_userprofile_delete_youtubeusercredential'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlaylistsRecord',
        ),
        migrations.DeleteModel(
            name='UserYoutubePlaylists',
        ),
    ]
