# Generated by Django 4.0.4 on 2023-02-17 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0004_channelsrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channelsrecord',
            name='channel_id',
            field=models.CharField(max_length=24, unique=True),
        ),
        migrations.AlterField(
            model_name='channelsrecord',
            name='channel_title',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
