# Generated by Django 4.0.4 on 2023-02-27 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0006_youtubeuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='youtubeuser',
            old_name='youtube_user_id',
            new_name='token_uri',
        ),
        migrations.RemoveField(
            model_name='youtubeuser',
            name='youtube_user_name',
        ),
    ]
