# Generated by Django 4.0.4 on 2023-02-28 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0007_rename_youtube_user_id_youtubeuser_token_uri_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='youtubeuser',
            name='token_uri',
        ),
    ]
