# Generated by Django 4.0.4 on 2023-02-28 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0008_remove_youtubeuser_token_uri'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='youtubeuser',
            table='YouTubeUsers',
        ),
    ]
